In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import r2_score,mean_squared_error
from m5py import M5Prime, export_text_m5

In [2]:
df = pd.read_excel("D:\BTP\Gopalkheda and yerli\calibration and validation__MLR\Gopalkheda_365.xlsx")
df

,Year,Month,Day,Discharge,RF1,RF2,RF3,RF4,RF5,RF6,...,RF123,RF124,RF125,RF126,RF127,Lumped rainfall gopalkheda,Lumped rainfall yerli,Q(t-1),Q(t-2),Q(t-3)
0,1977,6,1,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0
1,1977,6,2,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.0,0.0
2,1977,6,3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.0
3,1977,6,4,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.3
4,1977,6,5,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16066,2021,5,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1255,0.073053,0.0,0.0,0.0
16067,2021,5,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.0,2.9,0.0,0.0,0.8850,0.820913,0.0,0.0,0.0
16068,2021,5,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9,0.0,0.0,0.0,0.0,0.1924,0.307082,0.0,0.0,0.0
16069,2021,5,30,0.0,5.9,0.0,0.1,0.3,5.2,11.1,...,0.0,0.0,0.0,0.0,0.0,1.7709,3.300925,0.0,0.0,0.0
16070,2021,5,31,0.0,0.0,17.2,9.2,3.3,0.0,0.0,...,0.0,0.9,5.6,9.1,4.9,2.3075,2.011296,0.0,0.0,0.0

In [3]:
df1 = df[0:12418]
df2 = df[12418:]
df1

,Year,Month,Day,Discharge,RF1,RF2,RF3,RF4,RF5,RF6,...,RF123,RF124,RF125,RF126,RF127,Lumped rainfall gopalkheda,Lumped rainfall yerli,Q(t-1),Q(t-2),Q(t-3)
0,1977,6,1,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0
1,1977,6,2,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.0,0.0
2,1977,6,3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.0
3,1977,6,4,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.3
4,1977,6,5,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.3,0.3,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12413,2011,5,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0
12414,2011,5,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.5,0.0,0.0,0.0,0.4434,0.378076,0.0,0.0,0.0
12415,2011,5,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.6,0.0,0.0,0.0,0.0000,0.063752,0.0,0.0,0.0
12416,2011,5,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0
12417,2011,5,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0

In [4]:
df2

,Year,Month,Day,Discharge,RF1,RF2,RF3,RF4,RF5,RF6,...,RF123,RF124,RF125,RF126,RF127,Lumped rainfall gopalkheda,Lumped rainfall yerli,Q(t-1),Q(t-2),Q(t-3)
12418,2011,6,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.0,0.0,0.0
12419,2011,6,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0830,1.378468,0.0,0.0,0.0
12420,2011,6,3,0.0,5.7,5.1,6.8,1.0,2.3,7.0,...,0.6,0.0,1.4,5.1,0.8,1.6600,2.368115,0.0,0.0,0.0
12421,2011,6,4,0.0,24.0,0.0,4.5,10.0,15.0,34.3,...,0.0,0.4,2.1,0.0,0.0,1.2028,0.935607,0.0,0.0,0.0
12422,2011,6,5,0.0,5.9,3.2,2.1,0.2,2.4,0.0,...,0.0,0.0,0.0,0.0,0.0,1.2550,0.998581,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16066,2021,5,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1255,0.073053,0.0,0.0,0.0
16067,2021,5,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.0,2.9,0.0,0.0,0.8850,0.820913,0.0,0.0,0.0
16068,2021,5,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9,0.0,0.0,0.0,0.0,0.1924,0.307082,0.0,0.0,0.0
16069,2021,5,30,0.0,5.9,0.0,0.1,0.3,5.2,11.1,...,0.0,0.0,0.0,0.0,0.0,1.7709,3.300925,0.0,0.0,0.0
16070,2021,5,31,0.0,0.0,17.2,9.2,3.3,0.0,0.0,...,0.0,0.9,5.6,9.1,4.9,2.3075,2.011296,0.0,0.0,0.0

In [5]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-1)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-1)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.4243608003576057 123.97833654526387

In [6]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-1)","Q(t-2)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-1)","Q(t-2)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.45258397086799496 120.90085708974824

In [7]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-1)","Q(t-3)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-1)","Q(t-3)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.4100845040109353 125.50630010520318

In [8]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-2)","Q(t-3)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-2)","Q(t-3)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.1425883357446518 151.309194167684

In [9]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-1)","Q(t-2)","Q(t-3)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-1)","Q(t-2)" ,"Q(t-3)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.425098226068252 123.89889953695992

In [10]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-2)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-2)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.14942264206259048 150.70495566045878

In [11]:
model = M5Prime(use_pruning = True, use_smoothing = True)
model.fit(df1[["Q(t-3)"]].values,df1.Discharge.values)
predicted = model.predict(df2[["Q(t-3)"]].values)
print(r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

0.09957451306454645 155.05812010186744